### PR TITLE
Pr prix 2023

### PR DESCRIPTION
**Pull request by gcordonn**

### CODE REVIEW

**Review by dcoeurjo — APPROVED** [review]
Looks good to me

**Comment by dcoeurjo** [comment]
But it looks like there are conflicts with my edits

**Comment by gcordonn** [comment]
Yes I added back the quotation marks but with the correct formatting. I can't resolve the conflicts tho

**Comment by dcoeurjo** [comment]
only the photo has changed (compared to https://gdr-igrv.fr/resultats-prix-de-these/2023/) ?

**Comment by gcordonn** [comment]
no, content/resultats-prix-de-these/2023/index.md changed as well (add quotation marks + link to Anne Laure's thesis)

**Comment by dcoeurjo** [comment]
I've pushed the edits to the master

**Pull request closed without merging**
